### ISSUE TITLE
PHP check by SiteGround finds little bug

### ISSUE THREAD

**Issue by JensKirk** [digitoimistodude/woothemes-updater#1]
Hi 🙂

I just ran the new PHP checker from SiteGround and got the result below. Can it be fixed / improved?

Kind regards,
Jens
__________________________________________

FILE: /home/xxxxxxxxxx/public_html/xxxxxxxxx/wp-content/plugins/woothemes-updater/woothemes-updater.php
—————————————————————————————————————————————————–
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
—————————————————————————————————————————————————–
40 | WARNING | Function name “__woothemes_updater” is discouraged; PHP has reserved all method names with a double underscore prefix for future use
—————————————————————————————————————————————————–

**Comment by timiwahalahti** [comment]
Hi!

This is just a composer repository for woothemes-updater plugin and we don't maintain it. Plugin is maintained by Automattic and you should  [contact them](https://docs.woocommerce.com/document/woocommerce-helper/#section-26) regarding this :)
